import Head from "next/head";
import Header from "../components/Header";
import Login from "../components/Login";

function login() {
  return (
    <div>
        <Head>
        <title>Agri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AGRI (1).ico" />
      </Head>
      <Header />
      <Login />
    </div>
  );
}

export default login;
